# Config to extract SALSA-Lite for demo with 3 classes
data_dir: './data'
feature_dir: './features'
data:
  format: 'mic'
  fs: 48000
  n_fft: 512
  win_len: 512
  hop_len: 300  # 300 for 12.5ms for n_fft = 512; 150 for n_fft = 256
  fmin_doa: 50  # Hz
  fmax_doa: 2000 # Hz
